name: flutter_contacts_stack
description: "A powerful and high-performance Flutter plugin to access, modify, and manage device contacts across Android and iOS."
version: 1.0.4
homepage: https://github.com/stackobea/flutter_contacts_stack
repository: https://github.com/stackobea/flutter_contacts_stack
documentation: https://github.com/stackobea/flutter_contacts_stack
issue_tracker: https://github.com/stackobea/flutter_contacts_stack/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.stackobea.flutter_contacts_stack
        pluginClass: ContactsStackPlugin
      ios:
        pluginClass: FlutterContactsStackPlugin